// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAAj-lv-J78LV6x4Wq-oy-VyxAJZU-PMQ',
    appId: '1:621640731475:web:db0727f732c536bed3efa6',
    messagingSenderId: '621640731475',
    projectId: 'indivisual-ujjwal',
    authDomain: 'indivisual-ujjwal.firebaseapp.com',
    storageBucket: 'indivisual-ujjwal.appspot.com',
    measurementId: 'G-QSDB7MJRGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwpVYiKdNhegib0o7-cv_yw1mKGvlPti8',
    appId: '1:621640731475:android:b487cf606010e0d3d3efa6',
    messagingSenderId: '621640731475',
    projectId: 'indivisual-ujjwal',
    storageBucket: 'indivisual-ujjwal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh_pLUe5ioK3D1jt3tO1VVDq4gq021-lA',
    appId: '1:621640731475:ios:726cf77aeafce903d3efa6',
    messagingSenderId: '621640731475',
    projectId: 'indivisual-ujjwal',
    storageBucket: 'indivisual-ujjwal.appspot.com',
    iosClientId: '621640731475-i5t4gdk5ab4a4s8tdqqqm85c79rd079b.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh_pLUe5ioK3D1jt3tO1VVDq4gq021-lA',
    appId: '1:621640731475:ios:726cf77aeafce903d3efa6',
    messagingSenderId: '621640731475',
    projectId: 'indivisual-ujjwal',
    storageBucket: 'indivisual-ujjwal.appspot.com',
    iosClientId: '621640731475-i5t4gdk5ab4a4s8tdqqqm85c79rd079b.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
